import argparse

def get_train_args():
    p = argparse.ArgumentParser()
    p.add_argument('--emb_dir', type=str, required=True)
    p.add_argument('--epochs', type=int, default=20)
    p.add_argument('--batch_size', type=int, default=1024)
    p.add_argument('--lr', type=float, default=1e-3)
    p.add_argument('--proj_dim', type=int, default=512)
    p.add_argument('--weight_decay', type=float, default=1e-4)
    p.add_argument('--num_scales', type=int, default=8)
    p.add_argument('--r_min', type=float, default=0.1)
    p.add_argument('--r_max', type=float, default=5.0)
    p.add_argument('--alpha_mode', type=str, default='spectral', choices=['spectral','fixed'])
    p.add_argument('--alpha_fixed', type=float, default=1.5)
    p.add_argument('--learn_Q', type=lambda x: str(x).lower()=='true', default=True)
    p.add_argument('--Q_init', type=float, default=3.0)
    p.add_argument('--device', type=str, default='cuda')
    p.add_argument('--save_dir', type=str, default='checkpoints')
    p.add_argument('--log_every', type=int, default=50)
    p.add_argument('--eval_every', type=int, default=1)
    return p.parse_args()

def get_eval_args():
    p = argparse.ArgumentParser()
    p.add_argument('--emb_dir', type=str, required=True)
    p.add_argument('--ckpt', type=str, required=True)
    p.add_argument('--num_scales', type=int, default=8)
    p.add_argument('--r_min', type=float, default=0.1)
    p.add_argument('--r_max', type=float, default=5.0)
    p.add_argument('--alpha_mode', type=str, default='spectral', choices=['spectral','fixed'])
    p.add_argument('--alpha_fixed', type=float, default=1.5)
    p.add_argument('--device', type=str, default='cuda')
    return p.parse_args()

def get_zsc_args():
    p = argparse.ArgumentParser()
    p.add_argument('--emb_dir', type=str, required=True)
    p.add_argument('--ckpt', type=str, required=True)
    p.add_argument('--prompts_file', type=str, required=True)
    p.add_argument('--device', type=str, default='cuda')
    return p.parse_args()
